CREATE TABLE IF NOT EXISTS systemUsers
(
    id    BIGSERIAL PRIMARY KEY ,
    login  VARCHAR(200) NOT NULL ,
    password VARCHAR(254) NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS systemusers_id_seq START WITH 3 INCREMENT BY 1;